// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuwiwuxvzexhyliralyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1d2l3dXh2emV4aHlsaXJhbHl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxODE0MjUsImV4cCI6MjA2NTc1NzQyNX0.Mooz5hfscQ8pSwqpAolOuUc5Lmq1MULjMttqDNtlmU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);